### ISSUE TITLE
Simple HTTP Authentication

### ISSUE THREAD

**Issue by mikekuzak** [flatcar/nebraska#385]
Hi,

It would be nice to have a simple HTTP authentication mechanism to allow for one admin user, especially when running in-house.

**Comment by joaquimrocha** [comment]
If you don't need security (because you're running it in a secure/internal network), does the `noop` auth work for you in this case?

**Comment by mikekuzak** [comment]
We are using noop at the moment. (no auth),  but it would still be good that only internal admins have access. I'm looking into using Traefik 2.0 as proxy with HTTP auth in front of Nebraska.
