### ISSUE TITLE
After enabling a channel, it get's disabled after a few seconds

### ISSUE THREAD

**Issue by echo-devnull** [flatcar/nebraska#662]
## Description

After enabling a channel, a few seconds later the channel get's "disabled" without really giving me any hint as to why.

The logs are also not very clear to me. (see attached)

## Impact

This means flatcar nodes do not get their upgrade fix ;-)

## Environment and steps to reproduce

This is nebraska `2.7.0` installed in Kubernetes using the helm chart.

## Expected behavior

That the channel stay's enabled and hands out upgrades

**Comment by pothos** [comment]
Without looking at the logs I think that sounds like "safe mode" being enabled. See this comment: https://github.com/flatcar/nebraska/issues/427#issuecomment-889388914

**Comment by echo-devnull** [comment]
Ah yes, safe mode was indeed stopping further deployments.. Probably because all nodes are staying in "on hold" mode... So that's my next challenge. Figuring out why they are in on hold mode even though the machine itself say:

(One of the machines that are "on hold"  according to nebraska. but not giving me a reason for the hold)
```
I0727 14:50:44.829499 4087288 update_engine_client.cc:241] Querying Update Engine status...
LAST_CHECKED_TIME=1690360753
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_IDLE
NEW_VERSION=0.0.0
NEW_SIZE=0
```

**Comment by echo-devnull** [comment]
![image](https://github.com/flatcar/nebraska/assets/5389465/66b8035a-55e5-4774-85ae-7c9441b29dc2)


Perhaps a feature request? to make the error show up in the events part of this page ;-)

**Comment by echo-devnull** [comment]
Well, this morning everything started upgrading again. I did nothing to make it that way.. soooo #magic     ;-)

**Comment by pothos** [comment]
In the instance view of Nebraska you should see the events that led to this but it requires finding the right instance.
With safe mode disabled it should continue, otherwise after a day of waiting it should also work again with safe mode.
